spring:
  application:
    name: eureka-server

server:
  port: 12345 # Eureka 不能使用随机可用端口

# Eureka 客户端连接配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      show-components: always